<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTClZRCh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTClZRCh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTClZRCh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTClZRCh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTClZRCh\App_KernelDevDebugContainer([
    'container.build_hash' => 'TClZRCh',
    'container.build_id' => '6993f4f9',
    'container.build_time' => 1583836458,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTClZRCh');
