<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJFEbl8h\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJFEbl8h/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJFEbl8h.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJFEbl8h\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJFEbl8h\App_KernelDevDebugContainer([
    'container.build_hash' => 'JFEbl8h',
    'container.build_id' => '9dbc1c15',
    'container.build_time' => 1583873609,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJFEbl8h');
