<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCboBvTG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCboBvTG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCboBvTG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCboBvTG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCboBvTG\App_KernelDevDebugContainer([
    'container.build_hash' => 'CboBvTG',
    'container.build_id' => 'b53c35be',
    'container.build_time' => 1583835721,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCboBvTG');
